services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timbas-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_DISCORD_ID=${ADMIN_DISCORD_ID}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
