version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timbas-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Configurações do Banco de Dados
      - DATABASE_URL=${DATABASE_URL}

      # Configurações do Admin
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_DISCORD_ID=${ADMIN_DISCORD_ID}

      # Configurações da API
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - timbas-network

  db:
    image: postgres:14
    container_name: timbas-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - timbas-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  timbas-network:
    driver: bridge
