export const DEMO_PREFIX = '[DEMO]';
export const DEMO_DISCORD_PREFIX = 'demo-timbas-';

export const DEMO_TEAM_NAMES = [
  'Fúria Azul',
  'Leões do Norte',
  'Trovão FC',
  'Guardiões',
  'Alvinegro',
  'Raposas',
  'Tricolor Real',
  'Vendaval',
  'Titãs do Vale',
  'Meteoro',
  'Panteras',
  'Estrela Solitária',
  'Dragões',
  'Rubro Forte',
  'Cometa',
  'Bravos',
  'Sentinelas',
  'Império',
  'Falcões',
  'Aurora',
  'Vulcão',
  'Colossos',
  'Nômades',
  'Relâmpago',
  'Pioneiros',
  'Titânio',
  'Andorinhas',
  'Muralha',
  'Cardeais',
  'Legião',
  'Corsários',
  'Ventania',
];

export const DEMO_POSITIONS = ['GOL', 'ZAG', 'ZAG', 'LD', 'LE', 'VOL', 'MC', 'MEI', 'PD', 'PE', 'ATA'];

export const DEMO_FIRST_NAMES = [
  'Caio',
  'Rafa',
  'Duda',
  'Léo',
  'Bruno',
  'Vitor',
  'Igor',
  'Théo',
  'Enzo',
  'Davi',
  'Murilo',
  'Otávio',
  'Yuri',
  'Nando',
  'Gustavo',
  'Kaique',
];

export const DEMO_LAST_NAMES = [
  'Andrade',
  'Barros',
  'Cardoso',
  'Dias',
  'Esteves',
  'Fontes',
  'Gomes',
  'Horta',
  'Ivo',
  'Junqueira',
  'Lacerda',
  'Moraes',
  'Nunes',
  'Prado',
  'Queiroz',
  'Rangel',
];
